version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/counter.txt:/app/counter.txt
    restart: always

  db:
    image: mysql:8.0
    container_name: recambios_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recambios
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
