version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - COUNTER_FILE=${APP_COUNTER_FILE}  # Pasar la variable a la app
    volumes:
      - ./app/counter.txt:/app/counter.txt
    restart: always

  db:
    image: mysql:8.0
    container_name: recambios_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
